---
- block:
    - name: Build frontend image
      community.docker.docker_image:
        name: "{{ frontend_image_name }}:latest"
        build:
          path: "{{ app_dir }}"
          dockerfile: "{{ frontend_dockerfile }}"
          nocache: yes
        source: build
        state: present
      tags: frontend-build

- name: Run frontend container
  community.docker.docker_container:
    name: yolo-frontend
    image: "{{ frontend_image_name }}:latest"
    state: started
    restart_policy: unless-stopped
    ports:
      - "3000:80"
    networks:
      - name: "{{ network_name }}"
    command: >
      sh -c "
        echo 'Waiting for backend alias to be available...';
        until nslookup backend >/dev/null 2>&1; do
          echo 'Backend not resolvable yet... sleeping 2s';
          sleep 2;
        done;
        echo 'Backend alias ready! Starting Nginx...';
        exec /docker-entrypoint.sh nginx -g 'daemon off;'
      "
  tags: frontend