---
- block:
    - name: Build frontend image
      community.docker.docker_image:
        name: "{{ frontend_image_name }}:latest"
        build:
          path: "{{ app_dir }}"
          dockerfile: "{{ frontend_dockerfile }}"
        source: build
        state: present
      tags: frontend-build

- name: Run frontend container
  community.docker.docker_container:
    name: yolo-frontend
    image: "{{ frontend_image_name }}:latest"
    state: started
    restart_policy: unless-stopped
    ports:
      - "3000:80"
    networks:
      - name: "{{ network_name }}"
    command: >-
      sh -c "
        echo 'Waiting for backend to be ready...';
        until ping -c1 backend >/dev/null 2>&1; do
          echo 'Backend not ready yet... sleeping 2s';
          sleep 2;
        done;
        echo 'Backend is ready! Starting Nginx...';
        exec nginx -g 'daemon off;'
      "
  tags: frontend